#! /bin/sh

#  _                                 
# | |__  ___ _ ____      ___ __ ___  
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|                      
#

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc config border_width        0 
bspc config window_gap          12
bspc config border_radius       10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Brave-browser desktop='^1'
bspc rule -a St desktop='^2'

wallpaper ~/wallpapers
~/.config/polybar/launch.sh &
killall picom
picom &
brave &
st &





